env:
  node: true
  es6: true
extends:
  - 'standard'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: babel-eslint
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  generator-star-spacing: off
  no-debugger: off
overrides:
  - files:
    - "./**/*.mjs"
